version: '3.8'

services:
  redis:
    image: redis:7.4
    container_name: redis-todo
    ports:
      - "6380:6379"
    volumes:
      - redis-todo:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "20001:20001"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    restart: unless-stopped
    tty: true

  gateway:
    build: ./gateway
    container_name: todo-gateway
    ports:
      - "20000:20000"
    depends_on:
      - backend
    restart: unless-stopped
    tty: true

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - gateway
    restart: unless-stopped

volumes:
  redis-todo:
    driver: local
