// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: todo.proto

package server

import (
	"context"

	"todo/backend/internal/logic"
	"todo/backend/internal/svc"
	"todo/backend/pb/pb"
)

type TodoServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTodoServiceServer
}

func NewTodoServiceServer(svcCtx *svc.ServiceContext) *TodoServiceServer {
	return &TodoServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TodoServiceServer) GetTodos(ctx context.Context, in *pb.GetTodosReq) (*pb.GetTodosResp, error) {
	l := logic.NewGetTodosLogic(ctx, s.svcCtx)
	return l.GetTodos(in)
}

func (s *TodoServiceServer) CreateTodo(ctx context.Context, in *pb.CreateTodoReq) (*pb.CreateTodoResp, error) {
	l := logic.NewCreateTodoLogic(ctx, s.svcCtx)
	return l.CreateTodo(in)
}

func (s *TodoServiceServer) UpdateTodo(ctx context.Context, in *pb.UpdateTodoReq) (*pb.UpdateTodoResp, error) {
	l := logic.NewUpdateTodoLogic(ctx, s.svcCtx)
	return l.UpdateTodo(in)
}

func (s *TodoServiceServer) DeleteTodo(ctx context.Context, in *pb.DeleteTodoReq) (*pb.DeleteTodoResp, error) {
	l := logic.NewDeleteTodoLogic(ctx, s.svcCtx)
	return l.DeleteTodo(in)
}
