// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"todo/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/createTodo",
				Handler: CreateTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/deleteTodo",
				Handler: DeleteTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/getTodos",
				Handler: GetTodosHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/updateTodo",
				Handler: UpdateTodoHandler(serverCtx),
			},
		},
	)
}
