// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: todo.proto

package todoservice

import (
	"context"

	"todo/backend/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateTodoReq  = pb.CreateTodoReq
	CreateTodoResp = pb.CreateTodoResp
	DeleteTodoReq  = pb.DeleteTodoReq
	DeleteTodoResp = pb.DeleteTodoResp
	GetTodosReq    = pb.GetTodosReq
	GetTodosResp   = pb.GetTodosResp
	Todo           = pb.Todo
	UpdateTodoReq  = pb.UpdateTodoReq
	UpdateTodoResp = pb.UpdateTodoResp

	TodoService interface {
		GetTodos(ctx context.Context, in *GetTodosReq, opts ...grpc.CallOption) (*GetTodosResp, error)
		CreateTodo(ctx context.Context, in *CreateTodoReq, opts ...grpc.CallOption) (*CreateTodoResp, error)
		UpdateTodo(ctx context.Context, in *UpdateTodoReq, opts ...grpc.CallOption) (*UpdateTodoResp, error)
		DeleteTodo(ctx context.Context, in *DeleteTodoReq, opts ...grpc.CallOption) (*DeleteTodoResp, error)
	}

	defaultTodoService struct {
		cli zrpc.Client
	}
)

func NewTodoService(cli zrpc.Client) TodoService {
	return &defaultTodoService{
		cli: cli,
	}
}

func (m *defaultTodoService) GetTodos(ctx context.Context, in *GetTodosReq, opts ...grpc.CallOption) (*GetTodosResp, error) {
	client := pb.NewTodoServiceClient(m.cli.Conn())
	return client.GetTodos(ctx, in, opts...)
}

func (m *defaultTodoService) CreateTodo(ctx context.Context, in *CreateTodoReq, opts ...grpc.CallOption) (*CreateTodoResp, error) {
	client := pb.NewTodoServiceClient(m.cli.Conn())
	return client.CreateTodo(ctx, in, opts...)
}

func (m *defaultTodoService) UpdateTodo(ctx context.Context, in *UpdateTodoReq, opts ...grpc.CallOption) (*UpdateTodoResp, error) {
	client := pb.NewTodoServiceClient(m.cli.Conn())
	return client.UpdateTodo(ctx, in, opts...)
}

func (m *defaultTodoService) DeleteTodo(ctx context.Context, in *DeleteTodoReq, opts ...grpc.CallOption) (*DeleteTodoResp, error) {
	client := pb.NewTodoServiceClient(m.cli.Conn())
	return client.DeleteTodo(ctx, in, opts...)
}
