// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateTodoReq struct {
	Title         string `json:"title"`
	IsOnlyForTest bool   `json:"is_only_for_test"`
}

type CreateTodoResp struct {
	Todo Todo `json:"todo"`
}

type DeleteTodoReq struct {
	Id string `json:"id"`
}

type DeleteTodoResp struct {
}

type GetTodosReq struct {
}

type GetTodosResp struct {
	Todos []Todo `json:"todos"`
}

type Todo struct {
	Id            string `json:"id"`
	Title         string `json:"title"`
	Completed     bool   `json:"completed"`
	IsOnlyForTest bool   `json:"is_only_for_test"`
}

type UpdateTodoReq struct {
	Id        string `json:"id"`
	Title     string `json:"title"`
	Completed bool   `json:"completed"`
}

type UpdateTodoResp struct {
}
